# Generated by Django 6.0.3 on 2026-03-14 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="join_date",
        ),
    ]
