# Generated by Django 6.0.3 on 2026-03-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0002_loanpayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanpayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
