# Generated by Django 4.2.23 on 2026-03-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0003_loanpayment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="loanpayment",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
